version: '3.1'

services:

  db:
    image: postgres:10.9
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: eccube4
    volumes:
      - ./data:/var/lib/postgresql/data

  mailcatcher:
          image: schickling/mailcatcher
          ports:
              - "1080:1080"
              - "1025:1025"